// <auto-generated />
using CoreTestingSample.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CoreTestingSample.Migrations
{
    [DbContext(typeof(TestingContext))]
    [Migration("20180425154242_InititalCreate")]
    partial class InititalCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("CoreTestingSample.Context.DataModels.Address", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("City");

                    b.Property<string>("Street");

                    b.Property<string>("Suite");

                    b.Property<string>("ZipCode");

                    b.HasKey("Id");

                    b.ToTable("address");
                });

            modelBuilder.Entity("CoreTestingSample.Context.DataModels.Company", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Bs");

                    b.Property<string>("CatchPhrase");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("company");
                });

            modelBuilder.Entity("CoreTestingSample.Context.DataModels.Person", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<Guid?>("AddressId");

                    b.Property<string>("Avatar");

                    b.Property<Guid?>("CompanyId");

                    b.Property<DateTimeOffset>("DateOfBirth");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Phone");

                    b.Property<string>("UserName");

                    b.Property<string>("Website");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CompanyId");

                    b.ToTable("person");
                });

            modelBuilder.Entity("CoreTestingSample.Context.DataModels.Person", b =>
                {
                    b.HasOne("CoreTestingSample.Context.DataModels.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("CoreTestingSample.Context.DataModels.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");
                });
#pragma warning restore 612, 618
        }
    }
}
